# Generated by Django 3.2.8 on 2021-12-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_alter_ads_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
