# Generated by Django 3.2.8 on 2021-12-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0004_auto_20211206_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ads',
            name='subject',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ads',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ads',
            name='writer',
            field=models.CharField(max_length=100),
        ),
    ]
